### ISSUE TITLE
Check Eq of power radiated in Infinite baffle speaker

### ISSUE THREAD

**Issue by sivanandareddy** [maqifrnswa/scimpy#20]
In equation 5.12 omega^2 is already taken in right hand part. How deos it still remain in the left hand part
In equation 5.14 and 5.15 when Z_e is expaned where does R_er (electrical equivalent of Radiation) is gone.

**Comment by maqifrnswa** [comment]
Wow - thank you! I'll look in to that. I'm back looking at this project again, and will be releasing a new version too as well
