### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mitscherdinger** [maqifrnswa/scimpy#23]
Hi, there!

With the latest git-version I can't run the installer. This is what I've done:

As root:
apt-get install python3-scipy python3-pyaudio python3-matplotlib python3-pyqt5 python3-pandas
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-matplotlib is already the newest version (2.0.0+dfsg1-2).
python3-pandas is already the newest version (0.19.2-5).
python3-pyqt5 is already the newest version (5.7+dfsg-5).
python3-pyaudio is already the newest version (0.2.10-1).
python3-scipy is already the newest version (0.18.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

As user:
python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

pip install scimpy
bash: pip: command not found

Have I missed something?

**Comment by maqifrnswa** [comment]
Thanks for testing, I'll update the install instructions:
instead of "pip install scimpy"
run:

```
python3 run.py
```

from the directory you synced from github.

I'm still trying to figure out the best way of distributing, but for now using the github repo like you're doing is best

**Comment by maqifrnswa** [comment]
I've eased installation, so I think this can be closed!
Windows:
https://ci.appveyor.com/project/maqifrnswa/scimpy/build/artifacts

Ubuntu:
```
sudo add-apt-repository ppa:showard314/scimpy
sudo apt-get update
sudo apt-get install scimpy
```
